[package]
name = "export"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.12.0"
rand = "0.8.4"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
