global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093
rule_files:
  - "/prometheus/rules/*.yml" 
scrape_configs:
  - job_name: grafana
    static_configs:
      - targets: ["127.0.0.1:9093"]
        labels:
          instance: prometheus
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9093"]
        labels:
          instance: prometheus
  - job_name: physical_machine
    static_configs:
      - targets: ["127.0.0.1:9273"]
  - job_name: metrics_rust
    static_configs:
      - targets: ["127.0.0.1:7777"]
  - job_name: node_exporter
    static_configs:
      - targets: ["127.0.0.1:9100"]
  - job_name: cadvisor
    static_configs:
      - targets: ['127.0.0.1:8080']
