apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
  - name: Prometheus AlertManager
    type: camptocamp-prometheus-alertmanager-datasource
    orgId: 1
    typeName: Prometheus AlertManager
    typeLogoUrl: public/plugins/camptocamp-prometheus-alertmanager-datasource/img/json-logo.svg
    access: proxy
    url: 127.0.0.1:9093
    password:
    user:
    database:
    basicAuth: false
    isDefault: false
    jsonData:
    readOnly: false
