{
 "title": "Docker overview with Cadvisor + docker state exporter + node exporter",
 "description": "Docker dashboard via Cadvisor + docker state exporter + node exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores{}) by (instance)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{}[5m]) * 100)by (instance) / sum(machine_cpu_cores{}) by (instance)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{}) by (instance) - sum(container_memory_cache{}) by (instance)) / sum(machine_memory_bytes{}) by (instance)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{}) by (instance) - sum(container_memory_cache{}) by (instance)"
    },
    {
     "expr": "sum(machine_memory_bytes{}) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{}[5m]))by (instance)"
    }
   ]
  },
  { "title": "Docker ( Cadvisor )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_last_seen) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Prometheus Exporter Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{}) / sum (machine_memory_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{})"
    }
   ]
  },
  {
   "title": "Containers Created",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 10, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "count by(name) (count_over_time(container_last_seen{name=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (machine_memory_bytes{})" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{}[1m])) / count(node_cpu_seconds_total{}) * 100"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[15m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\".+\"})/86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_state_status{name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}