{
 "title": "生产线-监控",
 "description": "系统资源指标明细图表：CPU 内存 磁盘 IO 网络等监控指标",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "间隔", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "生产监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "服务器资源总览【主机总数：$total】",
   "type": "table",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\n连接数：CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数。\n\n健康值是一个新增的指标，根据CPU，内存，IO计算出来的一个值，低于90分说明系统的资源使用情况需要注意",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_uname_info{} - 0", "legendFormat": "主机名" },
    {
     "expr": "sum(time() - node_boot_time_seconds{})/86400",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{}) ",
     "legendFormat": "总核数"
    },
    { "expr": "node_load5{}", "legendFormat": "5分钟负载" },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval]))) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{}[$interval]))",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{}[$interval]))",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{} - 0",
     "legendFormat": "连接数"
    },
    { "expr": "node_sockstat_TCP_tw{} - 0", "legendFormat": "TIME_WAIT" },
    {
     "expr": "max(rate(node_network_receive_bytes_total{}[$interval])*8)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{}[$interval])*8)",
     "legendFormat": "上传带宽"
    },
    {
     "expr": "((1-(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) )^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{}))^6)^(1/3)*0.3 + \r\n(1 - max(irate(node_disk_io_time_seconds_total{}[$interval]))^1.1)^(1/2)*0.2)*100",
     "legendFormat": "健康评分"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{}[$interval])) *100",
     "legendFormat": "IOutil使用率"
    }
   ]
  },
  {
   "title": "生产线卷信息",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 6 },
   "targets": [
    { "expr": "app_process_start{}" },
    { "expr": "app_process_get_nil_frame{}", "legendFormat": "收到帧数据为空情况" },
    {
     "expr": "app_process_get_small_y_frame{}",
     "legendFormat": "收到帧距离变小情况"
    },
    { "expr": "app_process_get_zero_y_frame{}", "legendFormat": "收到帧距离为0情况" },
    { "expr": "app_process_volume_id{}", "legendFormat": "当前卷号" },
    { "expr": "app_process_volume_info{}", "legendFormat": "每一卷总帧数" }
   ]
  },
  {
   "title": "收到的帧距",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    { "expr": "app_process_global_distance{}", "legendFormat": "收到的帧距离" }
   ]
  },
  {
   "title": "存储队列监控",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "app_process_pipeline_filter_chan_len{}",
     "legendFormat": "帧过滤队列堵塞数定时监控"
    },
    {
     "expr": "app_process_pipeline_handle_chan_len{}",
     "legendFormat": "帧处理队列堵塞数定时监控"
    },
    {
     "expr": "app_process_volume_data_chan_len{}",
     "legendFormat": "存储接收队列堵塞数定时监控"
    },
    {
     "expr": "app_process_volume_store_chan_len{}",
     "legendFormat": "存储写入队列堵塞数定时监控"
    },
    {
     "expr": "app_process_pipeline_receive_chan_len{}",
     "legendFormat": "帧接收队列堵塞数定时监控"
    }
   ]
  },
  {
   "title": "图数据定时监控",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "app_process_graph_data_chan_len{}",
     "legendFormat": "图数据接收队列堵塞数据定时监控"
    },
    {
     "expr": "app_process_graph_send_chan_len{}",
     "legendFormat": "图数据发送队列堵塞数据定时监控"
    }
   ]
  },
  {
   "title": "总帧数及耗时",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "app_process_graph_handle_frame_cost{}",
     "legendFormat": "耗时毫秒数"
    }
   ]
  },
  {
   "title": "系统资源监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(time() - node_boot_time_seconds{})",
     "legendFormat": "运行时间",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(node_cpu_seconds_total{ mode='system'})",
     "legendFormat": "CPU 核数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(node_memory_MemTotal_bytes{})",
     "legendFormat": "总内存",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "CPU iowait",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "node_filefd_maximum{}",
     "legendFormat": "总文件描述符",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "process_max_fds{}",
     "legendFormat": "最大进程打开文件",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "总内存" },
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{}",
     "legendFormat": "可用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / (node_memory_MemTotal_bytes{})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "进程运行状态",
   "type": "graph",
   "gridPos": { "h": 13, "w": 5, "x": 13, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{}",
     "legendFormat": "运行态的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{}",
     "legendFormat": "等待IO完成阻塞的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[$interval])) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[$interval])) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[$interval])) *100",
     "legendFormat": "磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "1分钟负载" },
    { "expr": "node_load5{}", "legendFormat": "5分钟负载" },
    { "expr": "node_load15{}", "legendFormat": "15分钟负载" },
    {
     "expr": " sum(count(node_cpu_seconds_total{mode='system'}) by (cpu)) ",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{}[$interval])",
     "legendFormat": "{{device}}_写入"
    },
    { "expr": "node_disk_io_now{}", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "系统指标抓取时间",
   "type": "graph",
   "description": "追踪 Prometheus 从 Node Exporter 抓取（scrape）指标的时间",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "秒" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{}",
     "legendFormat": "{{collector}} - Scrape duration"
    }
   ]
  }
 ]
}