{
 "title": "系统-Telegraf",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU 使用占比",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU 总核数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_n_cpus{}" }
   ]
  },
  {
   "title": "CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\"}"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}"
    },
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "CPU Core -System",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu!=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "CPU Core -User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "cpu_usage_user{cpu!=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mem_used_percent{}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "mem_buffered{}" },
    { "expr": "mem_cached{}" },
    { "expr": "mem_free{}" },
    { "expr": "mem_total{}" }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "system_load1{}" },
    { "expr": "system_load5{}" },
    { "expr": "system_load15{}" }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "processes_blocked{}" },
    { "expr": "processes_dead{}" },
    { "expr": "processesidle{}" },
    { "expr": "processes_paging{}" },
    { "expr": "processes_running{}" },
    { "expr": "processes_sleeping{}" },
    { "expr": "processes_stopped{}" },
    { "expr": "processes_zombies{}" }
   ]
  },
  {
   "title": "Disk used ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_used_percent{disk_device!=\"All\"}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{interface!~\"lo\"}[1m])"
    },
    {
     "expr": "rate(net_bytes_sent{interface!~\"lo\"}[1m])"
    }
   ]
  }
 ]
}