global:
  resolve_timeout: 5m

route:
  group_by: ["alertname","severity","service"]  
  group_wait: 10s 
  group_interval: 10s 
  repeat_interval: 10s 
  receiver: default
  # routes:  
  # - receiver: default  
  #   group_wait: 10s

receivers:
  - name: "default"
    webhook_configs: # this is a webhook test.
      - url: "http://127.0.0.1:4444/alertmanager/webhook"
        send_resolved: true

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['instance']
